export const templateFields = {
  'kawaii-letter': [
    { key: 'hint', label: 'Scene 1 Hint', type: 'input', placeholder: 'Tap seal to open ♥' },
    { key: 'scene2Header', label: 'Scene 2 Header', type: 'input', placeholder: 'A letter for you...' },
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your letter here...' },
    { key: 'scene3Header', label: 'Letter Bridge Line', type: 'input', placeholder: 'Our favorite memories' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Forever yours ♥' },
  ],
  '100-reasons': [
    { key: 'introText', label: 'Intro Message', type: 'textarea', placeholder: 'Before you read these...' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'With all my love ♥' },
  ],
  'our-gallery': [
    { key: 'galleryTitle', label: 'Gallery Title', type: 'input', placeholder: 'Our Story in Photos' },
    { key: 'introText', label: 'Intro Message', type: 'textarea', placeholder: 'Every photo is a memory I treasure...' },
    { key: 'polaroidCaption1', label: 'Caption 1', type: 'input', placeholder: 'First memory ✨' },
    { key: 'polaroidCaption2', label: 'Caption 2', type: 'input', placeholder: 'That perfect day 🌟' },
    { key: 'polaroidCaption3', label: 'Caption 3', type: 'input', placeholder: 'Us always 💕' },
    { key: 'polaroidCaption4', label: 'Caption 4', type: 'input', placeholder: 'Golden hour 🌅' },
    { key: 'polaroidCaption5', label: 'Caption 5', type: 'input', placeholder: 'My favorite smile 😊' },
  ],
  'dark-romance': [
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your letter here...' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Yours always' },
  ],
  'our-story': [
    { key: 'storyTitle', label: 'Book Title', type: 'input', placeholder: 'Our Storybook' },
    { key: 'startDate', label: 'Date We Met', type: 'input', placeholder: 'June 14, 2021' },
    { key: 'chapter1Title', label: 'Chapter 1 Title', type: 'input', placeholder: 'How We Met' },
    { key: 'chapter1Text', label: 'Chapter 1 Text', type: 'textarea', placeholder: 'It all started when...' },
    { key: 'chapter2Title', label: 'Chapter 2 Title', type: 'input', placeholder: 'Our First Date' },
    { key: 'chapter2Text', label: 'Chapter 2 Text', type: 'textarea', placeholder: 'I remember being so nervous...' },
    { key: 'polaroidCaption1', label: 'Photo Caption 1', type: 'input', placeholder: 'Our first road trip' },
    { key: 'polaroidCaption2', label: 'Photo Caption 2', type: 'input', placeholder: 'The best coffee date' },
    { key: 'polaroidCaption3', label: 'Photo Caption 3', type: 'input', placeholder: 'Sunset with you' },
    { key: 'polaroidCaption4', label: 'Photo Caption 4', type: 'input', placeholder: 'A memory I replay often' },
    { key: 'polaroidCaption5', label: 'Photo Caption 5', type: 'input', placeholder: 'Forever favorite moment' },
    { key: 'letterTitle', label: 'Final Letter Title', type: 'input', placeholder: 'A Letter For You' },
    { key: 'finalLetter', label: 'Final Letter', type: 'textarea', placeholder: 'Write the closing letter that appears on the last page...' },
    { key: 'closingMessage', label: 'Fallback Closing Message', type: 'textarea', placeholder: 'And our story is only getting better...' },
  ],
  'midnight-love': [
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Under a thousand stars...' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Yours under every star ✨' },
  ],
  'sky-love': [
    { key: 'hint', label: 'Envelope Hint', type: 'input', placeholder: 'Tap the moon seal to open ✨' },
    { key: 'scene2Header', label: 'Scene 2 Header', type: 'input', placeholder: 'For you, beneath the stars' },
    { key: 'scene3Header', label: 'Scene 3 Header', type: 'input', placeholder: 'Tonight the sky keeps your name' },
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your sky love letter here...' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Always yours under this sky.' },
  ],
  'chat-reveal': [
    { key: 'chatSenderName', label: 'Chat Sender Name', type: 'input', placeholder: 'baby 🩷' },
    { key: 'chatSenderAvatar', label: 'Chat Sender Avatar', type: 'input', placeholder: '🩷' },
    { key: 'chatIntroTitle', label: 'Start Screen Title', type: 'input', placeholder: 'you have a message' },
    { key: 'chatIntroSubtitle', label: 'Start Screen Subtitle', type: 'input', placeholder: 'tap anywhere to open' },
    { key: 'chatScript', label: 'Chat Script (one line per message)', type: 'textarea', placeholder: 'them: hey\nme: hey\nthem: love: i love you 🩷' },
  ],
  'rose-whisper': [
    { key: 'hint', label: 'Envelope Hint', type: 'input', placeholder: 'A soft note just for you...' },
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your letter here...' },
    { key: 'scene2Header', label: 'Letter Header', type: 'input', placeholder: 'My Rose Whisper...' },
    { key: 'scene3Header', label: 'Memories Header', type: 'input', placeholder: 'Little moments of us' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Forever in bloom ♥' },
  ],
  'golden-promise': [
    { key: 'hint', label: 'Envelope Hint', type: 'input', placeholder: 'Open to read a golden promise ✨' },
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your promise here...' },
    { key: 'scene2Header', label: 'Letter Header', type: 'input', placeholder: 'A promise from my heart' },
    { key: 'scene3Header', label: 'Memories Header', type: 'input', placeholder: 'Memories I treasure' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'You are my always.' },
  ],
  'date-invite': [
    { key: 'introLine', label: 'Intro Line', type: 'input', placeholder: "There's something I have been wanting to ask..." },
    { key: 'hint', label: 'Envelope Hint', type: 'input', placeholder: 'Tap seal to open ♥' },
    { key: 'confessionTitle', label: 'Confessions Header', type: 'input', placeholder: 'But first, let me tell you...' },
    { key: 'confession1Text', label: 'Confession 1', type: 'input', placeholder: 'Your smile resets my whole day.' },
    { key: 'confession2Text', label: 'Confession 2', type: 'input', placeholder: 'You make ordinary moments feel cinematic.' },
    { key: 'confession3Text', label: 'Confession 3', type: 'input', placeholder: 'I still get excited every time your name appears.' },
    { key: 'confession4Text', label: 'Confession 4', type: 'input', placeholder: 'My calmest place is right next to you.' },
    { key: 'confession5Text', label: 'Confession 5', type: 'input', placeholder: 'You are my favorite person to celebrate life with.' },
    { key: 'confession6Text', label: 'Confession 6', type: 'input', placeholder: 'I like you. A lot. Maybe forever.' },
    { key: 'memoriesTitle', label: 'Memories Header', type: 'input', placeholder: 'Remember these?' },
    { key: 'polaroidCaption1', label: 'Memory Caption 1', type: 'input', placeholder: 'Our first little adventure' },
    { key: 'polaroidCaption2', label: 'Memory Caption 2', type: 'input', placeholder: 'When we laughed all night' },
    { key: 'polaroidCaption3', label: 'Memory Caption 3', type: 'input', placeholder: 'A day I keep replaying' },
    { key: 'polaroidCaption4', label: 'Memory Caption 4', type: 'input', placeholder: 'Coffee, rain, and your smile' },
    { key: 'polaroidCaption5', label: 'Memory Caption 5', type: 'input', placeholder: 'The moment I knew' },
    { key: 'continueLabel', label: 'Confessions Button Text', type: 'input', placeholder: 'Continue' },
    { key: 'questionCta', label: 'Memories Button Text', type: 'input', placeholder: 'Ask the question' },
    { key: 'questionTitle', label: 'Question Title', type: 'input', placeholder: 'Will you be my Valentine?' },
    { key: 'questionSubtitle', label: 'Question Subtitle', type: 'input', placeholder: 'A playful yes means everything to me.' },
    { key: 'yesLabel', label: 'Yes Button Label', type: 'input', placeholder: 'Yes, absolutely' },
    { key: 'noLabel', label: 'No Button Label', type: 'input', placeholder: 'No' },
    { key: 'noTaunt1', label: 'No Taunt 1', type: 'input', placeholder: 'Are you sure?' },
    { key: 'noTaunt2', label: 'No Taunt 2', type: 'input', placeholder: 'Nice try 😏' },
    { key: 'noTaunt3', label: 'No Taunt 3', type: 'input', placeholder: 'I can wait all day 💘' },
    { key: 'celebrationTitle', label: 'Celebration Title', type: 'input', placeholder: "I knew you would say yes!" },
    { key: 'celebrationText', label: 'Celebration Message', type: 'textarea', placeholder: 'Now we celebrate this moment and make it unforgettable.' },
  ],
  'iva-birthday': [
    { key: 'accessName', label: 'Gate Name', type: 'input', placeholder: 'iva' },
    { key: 'accessPassword', label: 'Gate Password', type: 'input', placeholder: 'love' },
    { key: 'welcomeTitle', label: 'Welcome Title', type: 'input', placeholder: 'Welcome, my love 💙' },
    { key: 'welcomeSubtitle', label: 'Welcome Subtitle', type: 'input', placeholder: 'This is our little private world.' },
    { key: 'questionTitle', label: 'Question Title', type: 'input', placeholder: 'Will you keep choosing me forever? 💍' },
    { key: 'homeTitle', label: 'Home Title', type: 'input', placeholder: 'Happy Birthday, my love 💙' },
    { key: 'homeSubtitle', label: 'Home Subtitle', type: 'input', placeholder: 'Every click is a little reminder of how much I love you.' },
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your birthday message...' },
    { key: 'galleryTitle', label: 'Gallery Title', type: 'input', placeholder: 'Our Moments 📸' },
    { key: 'gallerySubtitle', label: 'Gallery Subtitle', type: 'input', placeholder: 'A collection of our favorite memories.' },
    { key: 'reasonsTitle', label: 'Reasons Title', type: 'input', placeholder: 'Reasons I Love You 💙' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'I love you the most.' },
    { key: 'polaroidCaption1', label: 'Photo Caption 1', type: 'input', placeholder: 'You and your beautiful smile' },
    { key: 'polaroidCaption2', label: 'Photo Caption 2', type: 'input', placeholder: 'A day I will always remember' },
    { key: 'polaroidCaption3', label: 'Photo Caption 3', type: 'input', placeholder: 'My favorite moment' },
    { key: 'polaroidCaption4', label: 'Photo Caption 4', type: 'input', placeholder: 'Another reason to smile' },
    { key: 'polaroidCaption5', label: 'Photo Caption 5', type: 'input', placeholder: 'Us, just like this' },
    { key: 'startDate', label: 'Together Since (YYYY-MM-DD)', type: 'input', placeholder: '2025-12-06' },
  ],
}
