export const templateFields = {
  'kawaii-letter': [
    { key: 'hint', label: 'Scene 1 Hint', type: 'input', placeholder: 'Tap seal to open ♥' },
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your letter here...' },
    { key: 'scene2Header', label: 'Scene 2 Header', type: 'input', placeholder: 'A letter for you...' },
    { key: 'scene3Header', label: 'Scene 3 Header', type: 'input', placeholder: 'Our Memories' },
    { key: 'polaroidCaption1', label: 'Polaroid Caption 1', type: 'input', placeholder: 'First memory ✨' },
    { key: 'polaroidCaption2', label: 'Polaroid Caption 2', type: 'input', placeholder: 'That perfect day 🌟' },
    { key: 'polaroidCaption3', label: 'Polaroid Caption 3', type: 'input', placeholder: 'Us always 💕' },
    { key: 'polaroidCaption4', label: 'Polaroid Caption 4', type: 'input', placeholder: 'Golden hour 🌅' },
    { key: 'polaroidCaption5', label: 'Polaroid Caption 5', type: 'input', placeholder: 'My favorite smile 😊' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Forever yours ♥' },
  ],
  '100-reasons': [
    { key: 'introText', label: 'Intro Message', type: 'textarea', placeholder: 'Before you read these...' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'With all my love ♥' },
  ],
  'our-gallery': [
    { key: 'galleryTitle', label: 'Gallery Title', type: 'input', placeholder: 'Our Story in Photos' },
    { key: 'introText', label: 'Intro Message', type: 'textarea', placeholder: 'Every photo is a memory I treasure...' },
    { key: 'polaroidCaption1', label: 'Caption 1', type: 'input', placeholder: 'First memory ✨' },
    { key: 'polaroidCaption2', label: 'Caption 2', type: 'input', placeholder: 'That perfect day 🌟' },
    { key: 'polaroidCaption3', label: 'Caption 3', type: 'input', placeholder: 'Us always 💕' },
    { key: 'polaroidCaption4', label: 'Caption 4', type: 'input', placeholder: 'Golden hour 🌅' },
    { key: 'polaroidCaption5', label: 'Caption 5', type: 'input', placeholder: 'My favorite smile 😊' },
  ],
  'dark-romance': [
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your letter here...' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Yours always' },
  ],
  'our-story': [
    { key: 'startDate', label: 'Date We Met', type: 'input', placeholder: 'June 14, 2021' },
    { key: 'chapter1Title', label: 'Chapter 1 Title', type: 'input', placeholder: 'How We Met' },
    { key: 'chapter1Text', label: 'Chapter 1 Text', type: 'textarea', placeholder: 'It all started when...' },
    { key: 'chapter2Title', label: 'Chapter 2 Title', type: 'input', placeholder: 'Our First Date' },
    { key: 'chapter2Text', label: 'Chapter 2 Text', type: 'textarea', placeholder: 'I remember being so nervous...' },
    { key: 'closingMessage', label: 'Closing Message', type: 'textarea', placeholder: 'And the story continues...' },
  ],
  'midnight-love': [
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Under a thousand stars...' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Yours under every star ✨' },
  ],
  'rose-whisper': [
    { key: 'hint', label: 'Envelope Hint', type: 'input', placeholder: 'A soft note just for you...' },
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your letter here...' },
    { key: 'scene2Header', label: 'Letter Header', type: 'input', placeholder: 'My Rose Whisper...' },
    { key: 'scene3Header', label: 'Memories Header', type: 'input', placeholder: 'Little moments of us' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'Forever in bloom ♥' },
  ],
  'golden-promise': [
    { key: 'hint', label: 'Envelope Hint', type: 'input', placeholder: 'Open to read a golden promise ✨' },
    { key: 'letterText', label: 'Letter Text', type: 'textarea', placeholder: 'Write your promise here...' },
    { key: 'scene2Header', label: 'Letter Header', type: 'input', placeholder: 'A promise from my heart' },
    { key: 'scene3Header', label: 'Memories Header', type: 'input', placeholder: 'Memories I treasure' },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: 'You are my always.' },
  ],
  'date-invite': [
    { key: 'inviteHeadline', label: 'Invite Headline', type: 'input', placeholder: 'Will you go on a date with me?' },
    { key: 'inviteMessage', label: 'Invite Message', type: 'textarea', placeholder: 'I have a little plan for us...' },
    { key: 'dateWhen', label: 'Date & Time', type: 'input', placeholder: 'Saturday, 7:00 PM' },
    { key: 'dateWhere', label: 'Location', type: 'input', placeholder: 'Our favorite place' },
    { key: 'dressCode', label: 'Dress Code', type: 'input', placeholder: 'Come exactly as you are' },
    { key: 'rsvpContact', label: 'RSVP Note', type: 'input', placeholder: "Text me yes when you're ready 💌" },
    { key: 'closingMessage', label: 'Closing Message', type: 'input', placeholder: "I'd love to spend this evening with you." },
  ],
}
